### ISSUE TITLE
Automatic update of `Runner.Listener` fails.

### ISSUE THREAD

**Issue by kmdkuk** [cybozu-go/meows#48]
## What
The `Runner.Listener` will update itself when it receives a job if its version is old.
If this happens, the update will fail and the Pod will restart.
It does not reproduce reliably, but it has a high probability of occurring.
In github-actions-controller, if a Pod is restarted for some reason, it will be deleted and rebuilt to prevent reuse of the Pod.
If this happens at test runtime, the test will fail unintentionally.

I have confirmed that `Runner.Listener` output the following log when the update failed.

```
2021-07-20 07:18:44Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.278.0 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
Runner listener exited with error code 4
Runner listener exit with undefined return code, re-launch runner in 5 seconds.
Error: fork/exec /runner/bin/Runner.Listener: no such file or directory
```

Although the number of occurrences is small, i have also confirmed the following logs.

```
Failed to create a session. The runner registration has been deleted from the server, please re-configure.
Runner listener exited with error code 1
Runner listener exit with terminated error, stop the service, no retry needed.
Error: runner listener exit with terminated error: exit status 1
```

```
Registration was not found or is not medium trust. ClientType:
Error: exit status 1
```

## How

It is necessary to investigate the behavior when updating `Runner.Listener` and take appropriate measures.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

**Comment by masa213f** [comment]
https://github.com/cybozu-go/meows/pull/47
